#!/bin/bash

# Check if the correct number of arguments is provided
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <instance_id> <new_instance_type>"
    exit 1
fi

# Set your AWS region (change this to your desired region)
aws_region="ap-south-1"

# Extract command-line arguments
instance_id="$1"
new_instance_type="$2"

# Stop the instance
aws ec2 stop-instances --instance-ids "$instance_id" --region "$aws_region"

# Wait for the instance to stop
aws ec2 wait instance-stopped --instance-ids "$instance_id" --region "$aws_region"

# Modify the instance type
aws ec2 modify-instance-attribute --instance-id "$instance_id" --instance-type "{\"Value\":\"$new_instance_type\"}" --region "$aws_region"

# Start the instance
aws ec2 start-instances --instance-ids "$instance_id" --region "$aws_region"

# Wait for the instance to start
aws ec2 wait instance-running --instance-ids "$instance_id" --region "$aws_region"

echo "Instance type for $instance_id changed to $new_instance_type"
